version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: tftchamp_backend
    command: "uvicorn main:app --host 0.0.0.0 --port 8000"
    ports:
      - "8000:8000"
    environment:
      - ATLAS_URI=${ATLAS_URI}
      - DB_NAME=${DB_NAME}
      - RIOT_API_KEY=${RIOT_API_KEY}
      - PATCH=${PATCH}
      - LATEST_RELEASE=${LATEST_RELEASE}

  shiny:
    build:
      context: ./shiny-frontend
      dockerfile: Dockerfile
    container_name: tftchamp_shiny
    environment:
      - API_BASE_URL=http://backend:8000
      - ATLAS_URI=${ATLAS_URI}
      - DB_NAME=${DB_NAME}
      - RIOT_API_KEY=${RIOT_API_KEY}
      - PATCH=${PATCH}
      - LATEST_RELEASE=${LATEST_RELEASE}
    ports:
      - "3838:3838"
    depends_on:
      - backend
